###recent_meal

GET 127.0.0.1:5000/personal_query/recent_meal?user_id=1
###remaining_money

GET 127.0.0.1:5000/personal_query/remaining_money?user_id=1
###total_spent
GET 127.0.0.1:5000/personal_querytotal_spent?user_id=1
###view_data
GET 127.0.0.1:5000/window/view_data?view_name=floor_1_1
###totalwin_vegpurchases
GET 127.0.0.1:5000/window/totalwin_vegpurchases?dish_id=1
###gettop5windows
GET 127.0.0.1:5000/window/gettop5windows
###gettop5veg
GET 127.0.0.1:5000/window/gettop5veg
###dine_in
GET 127.0.0.1:5000/personal_query/dine_in?Bid=1&Vid=1&Bnum=10000
###top3_spenders
GET 127.0.0.1:5000/personal_query/top3_spenders
### GET 请求测试获取座位信息
GET 127.0.0.1:5000/window/seats
### post 请求测试预定座位接口
POST http://127.0.0.1:5000/window/reserve_seat
Content-Type: application/json

{
    "seat_id": 1
}

### GET 请求测试获取指定食堂的座位信息
GET 127.0.0.1:5000/window/seats?canteen_id=2

### POST 请求测试预定指定食堂的座位
POST http://127.0.0.1:5000/window/reserve_seat
Content-Type: application/json

{
    "canteen_id": 2,
    "seat_id": 1
}